name: challenge_mention
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - hdbscan
  - seaborn
  - ipywidgets
  - ipykernel
  - pip
  - tqdm
  - transformers
